version: "3"

services:
  redis:
    container_name: redis
    restart: always
    image: redis:latest
  app:
    container_name: app
    restart: always
    links:
      - redis
    depends_on:
      - redis
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
      - ../timestamps_dir:/timestamps_dir
    command: sh -c "cd ./plug && daphne -b 0.0.0.0 -p 8000 plug.asgi:application"
  ftpd_server:
    image: stilliard/pure-ftpd:hardened
    container_name: ftpd_server
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - ../timestamps_dir:/timestamps_dir
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: ${FTP_USER_NAME}
      FTP_USER_PASS: ${FTP_USER_PASS}
      FTP_USER_HOME: ${FTP_USER_HOME}
      ADDED_FLAGS: "--tls=2"
      TLS_CN: "localhost"
      TLS_ORG: "TestOrg"
      TLS_C: "PL"
    restart: always